### ISSUE TITLE
Any update for this ?

### ISSUE THREAD

**Issue by betaboy44** [AnthonyCalandra/SMF-Modifications#1]
Hello

This thing looks too old and i doubted it will not work with present whmcs or smf,..can it be updated ?

regards

**Comment by AnthonyCalandra** [comment]
@betaboy44 I'm not very active within the SMF/WHMCS communities anymore so the best I can do is tell you to install this on a test forum and see if it works from there.

**Comment by betaboy44** [comment]
I think it will not work,..because whmcs v6 has totally changed their coding base,..and this tool 2 years old looks like only supporting whmcs v4 or v5.

regards
